version: '3'

services:
  mysql:
    image: mariadb:latest
    environment:
    - MYSQL_ROOT_PASSWORD=mailtrain
    - MYSQL_DATABASE=mailtrain
    - MYSQL_USER=mailtrain
    - MYSQL_PASSWORD=mailtrain
    volumes:
    - mysql-data:/var/lib/mysql

  redis:
    image: redis:latest
    volumes:
    - redis-data:/data

  mongo:
    image: mongo:focal
    volumes:
    - mongo-data:/data/db

  mailtrain:
    build:
      context: .
      dockerfile: Dockerfile-Develop
    environment:
    - WWW_PROXY=true
    - URL_BASE_TRUSTED=https://mailtrain.sherman-mccoy.duckdns.org
    - URL_BASE_SANDBOX=https://sbox-mailtrain.sherman-mccoy.duckdns.org
    - URL_BASE_PUBLIC=https://lists.sherman-mccoy.duckdns.org
    - ADMIN_PASSWORD="KRQhzX8isKeMs3Y*"
    ports:
    - "3000:3000"
    - "3003:3003"
    - "3004:3004"
    - "9229:9229"
    - "9230:9230"
    - "9231:9231"
    - "9236:9236"
    volumes:
    - ./:/app

volumes:
  mysql-data:
  redis-data:
  mongo-data:
