version: '3'

services:
  mysql:
    image: mariadb:latest
    environment:
    - MYSQL_ROOT_PASSWORD=mailtrain
    - MYSQL_DATABASE=mailtrain
    - MYSQL_USER=mailtrain
    - MYSQL_PASSWORD=mailtrain
    volumes:
    - mysql-data:/var/lib/mysql

  redis:
    image: redis:latest
    volumes:
    - redis-data:/data

  mongo:
    image: mongo:focal
    volumes:
    - mongo-data:/data/db

  mailtrain:
    build:
      context: .
      dockerfile: Dockerfile-Develop
    environment:
    - ADMIN_PASSWORD="KRQhzX8isKeMs3Y*"
    ports:
    - "3000:3000"
    - "3003:3003"
    - "3004:3004"
    - "9229-9280:9229-9280"
    volumes:
    - ./:/app

volumes:
  mysql-data:
  redis-data:
  mongo-data:
